name: CI
on:
  push:
    tags:        
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1.4
      - name: Print tag
        run: echo $GIT_TAG_NAME
